apiVersion: v1
kind: Service

metadata:
  name: workday-backend-service

spec:
  selector:
    app: workday-backend

  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 4001
    - name: http-4001
      protocol: TCP
      port: 4001
      targetPort: 4001

  type: LoadBalancer